"use client";

import { useMemo, useState, useTransition } from "react";
import { Edit3, Loader2, Save, Upload, X } from "lucide-react";
import { toast } from "sonner";
import { type AdminDefaultStoreProduct, updateAdminDefaultStoreProduct, uploadHomeCmsFile } from "@/actions/admin";
import { AdminResourceShell } from "./admin-resource-shell";

export function AdminDefaultProductsPage({ initialProducts }: { initialProducts: AdminDefaultStoreProduct[] }) {
  const [products, setProducts] = useState(initialProducts);
  const [filter, setFilter] = useState<"All" | "Prints" | "Wall Art">("All");
  const [draft, setDraft] = useState<AdminDefaultStoreProduct | null>(null);
  const [pending, startTransition] = useTransition();
  const visible = useMemo(() => products.filter((item) => ["Prints","Wall Art"].includes(item.category) && (filter === "All" || item.category === filter)).sort((a,b)=>(a.sortOrder??0)-(b.sortOrder??0)), [products, filter]);
  const save = () => {
    if (!draft) return;
    startTransition(async()=>{try{const saved=await updateAdminDefaultStoreProduct(draft._id,draft);setProducts((current)=>current.map((item)=>item._id===saved._id?saved:item));setDraft(null);toast.success("Default product updated");}catch(error){toast.error(error instanceof Error?error.message:"Update failed");}});
  };
  const upload = async(file?:File)=>{if(!file||!draft)return;try{const url=await uploadHomeCmsFile(file);setDraft({...draft,images:[url],previewImages:[url]});}catch(error){toast.error(error instanceof Error?error.message:"Upload failed");}};
  return <AdminResourceShell active="products" title="Default Prints & Wall Art" subtitle="Edit the admin-owned product templates, prices, variants and product images used when a default Store catalog is generated. Users can use these defaults, but they cannot create or delete the master templates.">
    <div className="mb-5 flex flex-wrap gap-2">{(["All","Prints","Wall Art"] as const).map((item)=><button key={item} onClick={()=>setFilter(item)} className={`h-10 border px-5 text-sm font-bold ${filter===item?"bg-[#111] text-white":"bg-white"}`}>{item}</button>)}</div>
    <div className="overflow-x-auto bg-white"><table className="w-full min-w-[850px] text-sm"><thead className="border-b bg-[#fafafa] text-left text-xs uppercase tracking-[0.14em] text-[#777]"><tr><th className="px-4 py-4">Image</th><th className="px-4 py-4">Product</th><th className="px-4 py-4">Category</th><th className="px-4 py-4">Base price</th><th className="px-4 py-4">Variants</th><th className="px-4 py-4">Status</th><th className="px-4 py-4 text-right">Action</th></tr></thead><tbody>{visible.map((product)=><tr key={product._id} className="border-b"><td className="px-4 py-4"><div className="size-20 overflow-hidden bg-[#eee]">{product.images?.[0]?<img src={product.images[0]} alt="" className="h-full w-full object-cover"/>:null}</div></td><td className="px-4 py-4"><b>{product.name}</b><p className="mt-1 text-xs text-[#777]">{product.slug}</p></td><td className="px-4 py-4">{product.category}</td><td className="px-4 py-4">${Number(product.price||0).toFixed(2)}</td><td className="px-4 py-4">{product.variants?.length??0}</td><td className="px-4 py-4">{product.active?"Active":"Inactive"}</td><td className="px-4 py-4 text-right"><button onClick={()=>setDraft(JSON.parse(JSON.stringify(product)))} className="p-2 hover:bg-[#f3f3f3]"><Edit3 className="size-4"/></button></td></tr>)}</tbody></table></div>
    {draft&&<div className="fixed inset-0 z-50 overflow-y-auto bg-black/55 p-4"><div className="mx-auto my-4 w-full max-w-4xl bg-white p-6 shadow-2xl"><div className="flex justify-between border-b pb-5"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#777]">Default product editor</p><h2 className="mt-2 text-2xl font-semibold">{draft.name}</h2></div><button onClick={()=>setDraft(null)}><X className="size-5"/></button></div><div className="mt-6 grid gap-6 md:grid-cols-2"><Field label="Product name" value={draft.name} onChange={(name)=>setDraft({...draft,name})}/><Field label="Category" value={draft.category} onChange={(category)=>setDraft({...draft,category})}/><Field label="Base price" value={String(draft.price??0)} onChange={(value)=>setDraft({...draft,price:Number(value)||0})} type="number"/><Field label="Extra shipping" value={String(draft.extraShipping??0)} onChange={(value)=>setDraft({...draft,extraShipping:Number(value)||0})} type="number"/><Area label="Description" value={draft.description??""} onChange={(description)=>setDraft({...draft,description})}/><Area label="Product information" value={draft.productInfo??""} onChange={(productInfo)=>setDraft({...draft,productInfo})}/><Area label="Production note" value={draft.productionNote??""} onChange={(productionNote)=>setDraft({...draft,productionNote})}/><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-[#777]">Product image</p><div className="mt-2 flex items-center gap-4">{draft.images?.[0]&&<img src={draft.images[0]} alt="" className="size-28 object-cover"/>}<label className="inline-flex h-11 cursor-pointer items-center gap-2 bg-[#111] px-4 text-sm font-bold text-white"><Upload className="size-4"/>Upload<input type="file" accept="image/*" className="hidden" onChange={(e)=>upload(e.target.files?.[0])}/></label></div></div></div>
      <div className="mt-7"><div className="flex items-center justify-between"><h3 className="font-bold">Size / option variants</h3><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft.active} onChange={(e)=>setDraft({...draft,active:e.target.checked})}/>Active template</label></div><div className="mt-3 max-h-80 overflow-y-auto border">{(draft.variants??[]).map((variant,index)=><div key={variant.id} className="grid gap-3 border-b p-3 sm:grid-cols-[1.5fr_120px_120px_80px]"><input value={variant.label} onChange={(e)=>setDraft({...draft,variants:draft.variants?.map((item,i)=>i===index?{...item,label:e.target.value}:item)})} className="h-10 border px-3 text-sm"/><input type="number" value={variant.price} onChange={(e)=>setDraft({...draft,variants:draft.variants?.map((item,i)=>i===index?{...item,price:Number(e.target.value)||0}:item)})} className="h-10 border px-3 text-sm"/><input type="number" value={variant.extraShipping??0} onChange={(e)=>setDraft({...draft,variants:draft.variants?.map((item,i)=>i===index?{...item,extraShipping:Number(e.target.value)||0}:item)})} className="h-10 border px-3 text-sm"/><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={!variant.hidden} onChange={(e)=>setDraft({...draft,variants:draft.variants?.map((item,i)=>i===index?{...item,hidden:!e.target.checked}:item)})}/>Visible</label></div>)}</div></div><div className="mt-7 flex justify-end gap-3"><button onClick={()=>setDraft(null)} className="h-11 border px-5 text-sm font-bold">Cancel</button><button onClick={save} disabled={pending} className="inline-flex h-11 items-center gap-2 bg-[#22bda7] px-6 text-sm font-bold text-white">{pending?<Loader2 className="size-4 animate-spin"/>:<Save className="size-4"/>}Save product</button></div></div></div>}
  </AdminResourceShell>;
}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(value:string)=>void;type?:string}){return <label className="grid gap-2"><span className="text-xs font-bold uppercase tracking-[0.12em] text-[#777]">{label}</span><input type={type} value={value} onChange={(e)=>onChange(e.target.value)} className="h-11 border px-3 text-sm"/></label>}
function Area({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="grid gap-2"><span className="text-xs font-bold uppercase tracking-[0.12em] text-[#777]">{label}</span><textarea value={value} onChange={(e)=>onChange(e.target.value)} className="min-h-28 border p-3 text-sm"/></label>}
