"use client";

import { useEffect, useState, type ReactNode } from "react";
import { AlignCenter, AlignLeft, AlignRight, Check, ImagePlus, RotateCcw, Smartphone, X } from "lucide-react";
import { toast } from "sonner";
import type { MobileGalleryApp, MobileGalleryCoverText, MobileGalleryProfile } from "@/api-hooks/use-mobile-gallery";
import { uploadMobileGalleryAsset } from "@/api-hooks/use-mobile-gallery";
import { MobileGalleryPublic } from "./mobile-gallery-public";
import { getMobileGalleryCoverDefaults, MobileGalleryThemePreview } from "./mobile-gallery-cover";

const coverPresets: Array<{ name: string; description: string; value: MobileGalleryCoverText }> = [
  { name: "Minimal", description: "Clean title and date", value: { eyebrow: "", subtitle: "", alignment: "left", verticalPosition: "bottom", fontPreset: "sans", titleSize: 42, letterSpacing: 1, uppercase: false, showDivider: true, showDate: true, contentWidth: 88, overlayColor: "#000000", overlayOpacity: 26, textColor: "#ffffff", shadowStrength: 26 } },
  { name: "Editorial", description: "Elegant serif story cover", value: { eyebrow: "A collection of moments", subtitle: "", alignment: "left", verticalPosition: "bottom", fontPreset: "serif", titleSize: 52, letterSpacing: 0, uppercase: false, showDivider: false, showDate: true, contentWidth: 82, overlayColor: "#000000", overlayOpacity: 32, textColor: "#ffffff", shadowStrength: 32 } },
  { name: "Centered", description: "Formal centered composition", value: { eyebrow: "Mobile Gallery", subtitle: "", alignment: "center", verticalPosition: "center", fontPreset: "serif", titleSize: 44, letterSpacing: 4, uppercase: true, showDivider: true, showDate: true, contentWidth: 90, overlayColor: "#000000", overlayOpacity: 38, textColor: "#ffffff", shadowStrength: 34 } },
  { name: "Cinematic", description: "Bold image-first cover", value: { eyebrow: "", subtitle: "A story told in photographs", alignment: "center", verticalPosition: "bottom", fontPreset: "sans", titleSize: 56, subtitleSize: 15, letterSpacing: 2, uppercase: true, showDivider: false, showDate: false, contentWidth: 94, overlayColor: "#101820", overlayOpacity: 46, textColor: "#ffffff", shadowStrength: 50 } },
];

export function MobileGalleryDesignEditor({ app, profile, updateApp }: { app: MobileGalleryApp; profile: MobileGalleryProfile; updateApp: any }) {
  const [draft, setDraft] = useState<MobileGalleryApp>(app);
  const [coverPickerOpen, setCoverPickerOpen] = useState(false);
  const [advancedOpen, setAdvancedOpen] = useState(true);
  useEffect(() => setDraft(app), [app]);

  const design = draft.design || {};
  const themeName = design.theme || "lark";
  const coverText = getMobileGalleryCoverDefaults(draft, themeName, design.coverStyle || "none", design.coverText);
  const patchDesign = (patch: Record<string, unknown>) => setDraft((current) => ({ ...current, design: { ...(current.design || {}), ...patch } }));
  const patchCoverText = (patch: Partial<MobileGalleryCoverText>) => setDraft((current) => ({ ...current, design: { ...(current.design || {}), coverText: { ...(current.design?.coverText || {}), ...patch } } }));
  const cover = draft.coverImage || draft.images?.[0]?.url;
  const focal = design.focal || { x: 50, y: 50 };

  async function uploadIcon(file?: File) {
    if (!file) return;
    try { const iconUrl = await uploadMobileGalleryAsset(file); setDraft((current) => ({ ...current, iconUrl })); }
    catch (error) { toast.error(error instanceof Error ? error.message : "Upload failed"); }
  }

  const save = () => updateApp.mutateAsync({ coverImage: draft.coverImage, iconUrl: draft.iconUrl, design: draft.design }).then(() => toast.success("Design saved")).catch((error: Error) => toast.error(error.message));

  return (
    <section className="grid gap-8 pt-7 lg:grid-cols-[minmax(0,1fr)_430px]">
      <div className="min-w-0">
        <Panel title="Cover Style">
          <div className="flex flex-wrap justify-end gap-5 pb-4 text-sm font-semibold text-[#18bfa6]"><button type="button" onClick={() => setCoverPickerOpen(true)} className="flex items-center gap-2"><ImagePlus className="size-4" /> Change photo</button><span className="text-[#777]">Click the photo to set focal point</span></div>
          <div className="grid grid-cols-3 gap-3">{(["full", "third", "none"] as const).map((style) => <button key={style} onClick={() => patchDesign({ coverStyle: style })} className={`border p-3 text-center sm:p-4 ${design.coverStyle === style ? "border-[#18bfa6]" : ""}`}><div className={`mx-auto h-24 w-14 rounded-xl bg-[#ddd] sm:h-28 sm:w-16 ${style === "third" ? "border-t-[34px] border-white sm:border-t-[38px]" : style === "none" ? "border-t-[66px] border-white sm:border-t-[75px]" : ""}`} /><p className="mt-3 text-xs capitalize sm:text-sm">{style}</p></button>)}</div>
          {cover && <div className="mt-6"><div className="relative aspect-[4/3] cursor-crosshair overflow-hidden bg-[#eee]" onClick={(event) => { const rect = event.currentTarget.getBoundingClientRect(); const x = Math.max(0, Math.min(100, ((event.clientX - rect.left) / rect.width) * 100)); const y = Math.max(0, Math.min(100, ((event.clientY - rect.top) / rect.height) * 100)); patchDesign({ focal: { x: Math.round(x), y: Math.round(y) } }); }}><img src={cover} alt="Cover focal preview" className="h-full w-full object-cover" style={{ objectPosition: `${focal.x}% ${focal.y}%` }} /><span className="pointer-events-none absolute size-5 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-white bg-[#18bfa6] shadow" style={{ left: `${focal.x}%`, top: `${focal.y}%` }} /></div><div className="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2"><Range label="Horizontal focal" value={focal.x} min={0} max={100} onChange={(value) => patchDesign({ focal: { x: value, y: focal.y } })} /><Range label="Vertical focal" value={focal.y} min={0} max={100} onChange={(value) => patchDesign({ focal: { x: focal.x, y: value } })} /></div></div>}
        </Panel>

        <Panel title="Theme">
          <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{(["echo", "spring", "lark", "sage"] as const).map((name) => <button key={name} onClick={() => patchDesign({ theme: name, coverText: {} })} className={`relative overflow-hidden border text-left capitalize ${design.theme === name ? "border-[#18bfa6] bg-[#f4fffc]" : ""}`}><MobileGalleryThemePreview theme={name} /><span className="block px-3 py-3 text-sm font-semibold">{name}</span>{design.theme === name && <Check className="absolute right-2 top-2 size-5 rounded-full bg-white p-0.5 text-[#18bfa6]" />}</button>)}</div>
          <p className="mt-4 text-xs leading-5 text-[#777]">Selecting a theme applies its recommended layout. You can customize every text setting below.</p>
        </Panel>

        <Panel title="Cover Maker">
          <div className="grid gap-3 sm:grid-cols-2">{coverPresets.map((preset) => <button key={preset.name} type="button" onClick={() => patchCoverText({ ...preset.value, title: coverText.title || draft.name })} className="border p-4 text-left transition hover:border-[#18bfa6] hover:bg-[#f7fffd]"><span className="font-semibold">{preset.name}</span><span className="mt-1 block text-xs text-[#777]">{preset.description}</span></button>)}</div>
          <div className="mt-6 grid gap-4"><TextField label="Eyebrow" value={coverText.eyebrow} placeholder="Mobile Gallery" onChange={(value) => patchCoverText({ eyebrow: value })} /><TextField label="Main Title" value={coverText.title} placeholder={draft.name} onChange={(value) => patchCoverText({ title: value })} /><label className="text-xs font-semibold">Subtitle<textarea value={coverText.subtitle} onChange={(event) => patchCoverText({ subtitle: event.target.value })} rows={3} placeholder="Optional short story or description" className="mt-2 w-full border p-3 font-normal outline-none focus:border-[#18bfa6]" /></label><TextField label="Custom Date Label" value={coverText.dateLabel} placeholder="Leave empty to use Event Date" onChange={(value) => patchCoverText({ dateLabel: value })} /></div>
          <div className="mt-6 flex flex-wrap items-center justify-between gap-3 border-y py-4"><button type="button" onClick={() => setAdvancedOpen((value) => !value)} className="font-semibold text-[#18bfa6]">{advancedOpen ? "Hide" : "Show"} advanced controls</button><button type="button" onClick={() => patchDesign({ coverText: {} })} className="flex items-center gap-2 text-sm text-[#777]"><RotateCcw className="size-4" /> Reset to theme</button></div>
          {advancedOpen && <div className="mt-6 grid gap-6">
            <div><p className="text-xs font-semibold">Text Alignment</p><div className="mt-2 grid grid-cols-3 gap-2">{(["left", "center", "right"] as const).map((alignment) => <button key={alignment} type="button" onClick={() => patchCoverText({ alignment })} className={`flex items-center justify-center border p-3 ${coverText.alignment === alignment ? "border-[#18bfa6] bg-[#f4fffc]" : ""}`}>{alignment === "left" ? <AlignLeft className="size-4" /> : alignment === "center" ? <AlignCenter className="size-4" /> : <AlignRight className="size-4" />}</button>)}</div></div>
            <div><p className="text-xs font-semibold">Vertical Position</p><div className="mt-2 grid grid-cols-3 gap-2">{(["top", "center", "bottom"] as const).map((position) => <button key={position} type="button" onClick={() => patchCoverText({ verticalPosition: position })} className={`border p-3 text-sm capitalize ${coverText.verticalPosition === position ? "border-[#18bfa6] bg-[#f4fffc]" : ""}`}>{position}</button>)}</div></div>
            <label className="text-xs font-semibold">Font Style<select value={coverText.fontPreset} onChange={(event) => patchCoverText({ fontPreset: event.target.value as MobileGalleryCoverText["fontPreset"] })} className="mt-2 h-11 w-full border px-3 font-normal"><option value="theme">Theme Default</option><option value="serif">Serif</option><option value="sans">Sans Serif</option><option value="mono">Monospace</option><option value="script">Script</option></select></label>
            <div className="grid gap-4 sm:grid-cols-2"><Range label="Title Size" value={coverText.titleSize} min={24} max={80} onChange={(value) => patchCoverText({ titleSize: value })} suffix="px" /><Range label="Subtitle Size" value={coverText.subtitleSize} min={11} max={28} onChange={(value) => patchCoverText({ subtitleSize: value })} suffix="px" /><Range label="Letter Spacing" value={coverText.letterSpacing} min={0} max={12} onChange={(value) => patchCoverText({ letterSpacing: value })} suffix="px" /><Range label="Text Width" value={coverText.contentWidth} min={45} max={100} onChange={(value) => patchCoverText({ contentWidth: value })} suffix="%" /><Range label="Overlay Opacity" value={coverText.overlayOpacity} min={0} max={85} onChange={(value) => patchCoverText({ overlayOpacity: value })} suffix="%" /><Range label="Text Shadow" value={coverText.shadowStrength} min={0} max={100} onChange={(value) => patchCoverText({ shadowStrength: value })} suffix="%" /></div>
            <div className="grid grid-cols-2 gap-4"><label className="text-xs font-semibold">Cover Text Color<input type="color" value={coverText.textColor || (design.coverStyle === "full" ? "#ffffff" : design.textColor || "#222222")} onChange={(event) => patchCoverText({ textColor: event.target.value })} className="mt-2 h-10 w-full" /></label><label className="text-xs font-semibold">Overlay Color<input type="color" value={coverText.overlayColor} onChange={(event) => patchCoverText({ overlayColor: event.target.value })} className="mt-2 h-10 w-full" /></label></div>
            <div className="grid gap-3 sm:grid-cols-3"><Toggle label="Show date" checked={coverText.showDate} onChange={(checked) => patchCoverText({ showDate: checked })} /><Toggle label="Show divider" checked={coverText.showDivider} onChange={(checked) => patchCoverText({ showDivider: checked })} /><Toggle label="Uppercase title" checked={coverText.uppercase} onChange={(checked) => patchCoverText({ uppercase: checked })} /></div>
          </div>}
        </Panel>

        <Panel title="Photos Layout & Color"><div className="grid grid-cols-2 gap-3">{(["vertical", "horizontal"] as const).map((layout) => <button key={layout} onClick={() => patchDesign({ layout })} className={`border p-4 capitalize ${design.layout === layout ? "border-[#18bfa6]" : ""}`}>{layout}</button>)}</div><p className="mt-3 text-xs text-[#777]">Vertical emphasizes portrait photos, and Horizontal emphasizes landscape photos.</p><p className="mt-6 text-xs font-semibold uppercase tracking-wider text-[#777]">Grid style</p><div className="mt-2 grid grid-cols-2 gap-3">{(["masonry", "grid"] as const).map((gridStyle) => <button key={gridStyle} onClick={() => patchDesign({ gridStyle })} className={`border p-4 capitalize ${design.gridStyle === gridStyle ? "border-[#18bfa6]" : ""}`}>{gridStyle}</button>)}</div><div className="mt-5 grid grid-cols-1 gap-4 sm:grid-cols-2"><label className="text-xs font-semibold">Background Color<input type="color" value={design.backgroundColor || "#ffffff"} onChange={(event) => patchDesign({ backgroundColor: event.target.value })} className="mt-2 h-10 w-full" /></label><label className="text-xs font-semibold">Text Color<input type="color" value={design.textColor || "#222222"} onChange={(event) => patchDesign({ textColor: event.target.value })} className="mt-2 h-10 w-full" /></label></div></Panel>
        <Panel title="App Icon"><div className="flex flex-wrap items-center gap-4">{draft.iconUrl ? <img src={draft.iconUrl} alt="" className="size-20 rounded-2xl object-cover" /> : <div className="flex size-20 items-center justify-center rounded-2xl bg-[#eee]"><Smartphone className="size-6" /></div>}<label className="relative cursor-pointer border px-4 py-2 text-sm">Upload Icon<input type="file" accept="image/*" className="absolute inset-0 cursor-pointer opacity-0" onChange={(event) => uploadIcon(event.target.files?.[0])} /></label></div><p className="mt-3 text-xs text-[#777]">Use a square image. It becomes the Android, desktop and iPhone home-screen icon.</p></Panel>
        <button onClick={save} disabled={updateApp.isPending} className="mt-6 bg-[#18bfa6] px-7 py-3 font-semibold text-white disabled:opacity-60">{updateApp.isPending ? "Saving…" : "Save Design"}</button>
      </div>
      <div className="lg:sticky lg:top-6 lg:h-fit"><PhonePreview><MobileGalleryPublic app={draft} profile={profile} embedded /></PhonePreview></div>
      {coverPickerOpen && <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-black/50 p-4"><div className="w-full max-w-3xl bg-white p-5 shadow-2xl sm:p-7"><div className="flex items-center justify-between gap-4"><div><h3 className="text-xl font-semibold">Change cover photo</h3><p className="mt-1 text-sm text-[#777]">Choose any photo already uploaded to this app.</p></div><button onClick={() => setCoverPickerOpen(false)}><X className="size-5" /></button></div><div className="mt-6 grid max-h-[65vh] grid-cols-2 gap-3 overflow-y-auto sm:grid-cols-4">{(draft.images || []).map((image) => <button key={image._id} onClick={() => { setDraft((current) => ({ ...current, coverImage: image.url })); setCoverPickerOpen(false); }} className={`relative border-2 ${draft.coverImage === image.url ? "border-[#18bfa6]" : "border-transparent"}`}><img src={image.thumbnailUrl || image.url} alt="" className="aspect-square w-full object-cover" />{draft.coverImage === image.url && <span className="absolute right-2 top-2 rounded-full bg-[#18bfa6] p-1 text-white"><Check className="size-4" /></span>}</button>)}</div>{!draft.images?.length && <p className="py-16 text-center text-sm text-[#777]">Upload photos in the Photos tab first.</p>}</div></div>}
    </section>
  );
}

function Panel({ title, children }: { title: string; children: ReactNode }) { return <section className="border-b py-7"><h2 className="mb-5 text-lg font-medium">{title}</h2>{children}</section>; }
function PhonePreview({ children }: { children: ReactNode }) { return <div className="mx-auto w-full max-w-[390px] rounded-[42px] bg-white p-3 shadow-[0_22px_60px_rgba(0,0,0,0.16)]"><div className="h-[min(720px,78vh)] min-h-[560px] overflow-hidden rounded-[32px] border bg-white">{children}</div></div>; }
function TextField({ label, value, placeholder, onChange }: { label: string; value: string; placeholder?: string; onChange: (value: string) => void }) { return <label className="text-xs font-semibold">{label}<input value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} className="mt-2 h-11 w-full border px-3 font-normal outline-none focus:border-[#18bfa6]" /></label>; }
function Range({ label, value, min, max, suffix = "", onChange }: { label: string; value: number; min: number; max: number; suffix?: string; onChange: (value: number) => void }) { return <label className="text-xs font-semibold"><span className="flex justify-between"><span>{label}</span><span className="font-normal text-[#777]">{value}{suffix}</span></span><input type="range" min={min} max={max} value={value} onChange={(event) => onChange(Number(event.target.value))} className="mt-2 w-full accent-[#18bfa6]" /></label>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (checked: boolean) => void }) { return <label className="flex cursor-pointer items-center gap-2 border p-3 text-sm"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} />{label}</label>; }
